name: Convert gameparams new

on:
  workflow_dispatch:
    inputs:
      gameVersion:
        description: 'Game version'
        required: true
        type: string
      server:
        description: 'Server'
        required: true
        default: live
        type: choice
        options:
          - live
          - pts

jobs: 
  convertAndUploadData:
    runs-on: ubuntu-latest
    name: Convert gameparams and upload data

    steps:
      - run: |
          echo "Server: $SERVER_TYPE"
          echo "Game version: $GAME_VERSION"
      - env:
          SERVER_TYPE: ${{ inputs.server }}
          GAME_VERSION: ${{ inputs.gameVersion }}
            
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: eu-central-1
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          
      - name: Prepare data converter
        run: dotnet test -c Release --verbosity normal

      - name: Define gameparams input
        run: echo "INPUT_PATH_ZIP=$(pwd)/zip/in" >> $GITHUB_ENV
        
      - name: Define gameparams input
        run: echo "GAMEPARAMS_DIRECTORY=$(pwd)/gameparams/in" >> $GITHUB_ENV
        
      - name: Define texts input
        run: echo "TEXTS_DIRECTORY=$(pwd)/gameparams/in/texts" >> $GITHUB_ENV

      - name: Define gameparams output
        run: echo "OUTPUT_PATH=$(pwd)/gameparams/out" >> $GITHUB_ENV

      - name: Download file from ASW
        uses: prewk/s3-cp-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: eu-central-1
          source: 's3://wows-shipbuilder-data/gamedata/$SERVER_TYPE'
          dest: '$INPUT_PATH_ZIP'
        
      - name: Unzip files
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq $NPUT_PATH_ZIP/data.zip -d $GAMEPARAMS_DIRECTORY
      
      - name: Run gameparams extraction
        run: dotnet run -c Release -- convert -s $SERVER_TYPE -p $GAMEPARAMS_DIRECTORY/GameParams_$SERVER_TYPE.data -l $TEXTS_DIRECTORY -o $OUTPUT_PATH -v $GAME_VERSION
        working-directory: DataConverter.Console
      
      - name: Backup old files
        run: aws s3 mv s3://wows-shipbuilder-data/api/$SERVER_TYPE s3://wows-shipbuilder-data/old/pre-$GAME_VERSION-$SERVER_TYPE --recursive
      - name: Upload files
        run: aws s3 sync "gameparams/out" "s3://wows-shipbuilder-data/api/$SERVER_TYPE" --exclude "*.csv"
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} --paths "/api/$SERVER_TYPE/*"
